apiVersion: v1
kind: Secret
metadata:
  name: media-db-secret
type: Opaque
stringData:
  # This tells Helm: "Look inside values.yaml and grab the password"
  password: {{ .Values.postgres.password }}
