apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"media-engine"},"name":"media-engine","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"media-engine"}}}
  creationTimestamp: "2026-02-08T13:16:09Z"
  labels:
    app: media-engine
  name: media-engine
  namespace: default
  resourceVersion: "108478"
  uid: bdbd7e71-2a58-4329-87eb-f48c953b2ce8
spec:
  clusterIP: 10.96.179.253
  clusterIPs:
  - 10.96.179.253
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: media-engine
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
